---
development:
  cloud_name: meelos
  api_key: '851971193328157'
  api_secret: eK1M7PJLurELp_w3f1luh9I1DJY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: meelos
  api_key: '851971193328157'
  api_secret: eK1M7PJLurELp_w3f1luh9I1DJY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: meelos
  api_key: '851971193328157'
  api_secret: eK1M7PJLurELp_w3f1luh9I1DJY
  enhance_image_tag: true
  static_file_support: false
